spring.application.name=demo


spring.datasource.url=jdbc:postgresql://localhost:5432/student_billing_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

server.port=3001

# CORS configuration
cors.allowed-origins=http://localhost:3000

# MyBatis mapper locations
mybatis-plus.mapper-locations=classpath*:mybatis/**/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=false

logging.level.org.apache.ibatis= DEBUG
logging.level.org.mybatis= DEBUG
logging.level.org.mybatis.spring.SqlSessionFactoryBean= DEBUG