spring.application.name=demo


spring.datasource.url=jdbc:postgresql://localhost:5432/student_billing_db
spring.datasource.username=postgres
spring.datasource.password=Geforce@2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

server.port=3001

# CORS configuration
cors.allowed-origins=http://localhost:3000